---
title: "Maps with inset"
author: "Author"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 6
vignette: >
  %\VignetteIndexEntry{Maps with inset}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Maps with inset for Oslo and Akershus

We start with the standard map `fhidata::norway_map_counties_b2020` and provide data:

```{r}
# start off with base map
pd <- fhimaps::norway_nuts3_map_b2020_insert_oslo_dt

# create some fictional data
data <- unique(pd[,c("location_code")])
suppressWarnings(data[,category:=rep(c("High","Medium","Low"),each=5)[1:.N]])
data[,category_with_missing:=category]
data[1,category_with_missing:="Missing"]
data[,category:=factor(category,levels=c("High","Medium","Low"))]
data[,category_with_missing:=factor(category_with_missing,levels=c("High","Medium","Low","Missing"))]
data[location_code == "county54", category:='Low']
data[location_code == "county54", category_with_missing:='Low']

# merge the data into the map
pd[data,on="location_code",category:=category]
pd[data,on="location_code",category_with_missing:=category_with_missing]
```

If your data does not contain any missing, then we recommend to use the `_complete` map palettes:

```{r fig.height=7, fig.width=7}
library(ggplot2)
library(splstyle)

q <- ggplot()
q <- q + geom_polygon(data = pd, aes( x = long, y = lat, group = group, fill=category), color="black")
q <- q + theme_void()
q <- q + coord_quickmap()
q <- q + splstyle::scale_fill_fhi("Category",palette = "map_seq_complete", direction = 1, drop=F)
q <- q + labs(title = "Palette = map_seq_complete")
q
```

```{r fig.height=7, fig.width=7}
library(ggplot2)
library(splstyle)

q <- ggplot()
q <- q + geom_polygon(data = pd, aes( x = long, y = lat, group = group, fill=category), color="black")
q <- q + theme_void()
q <- q + coord_quickmap()
q <- q + splstyle::scale_fill_fhi("Category",palette = "map_seq_x2_complete", direction = 1, drop=F)
q <- q + labs(title = "Palette = map_seq_x2_complete")
q
```

If your data does contain missing, then we recommend to use the `_missing` map palettes:

```{r fig.height=7, fig.width=7}
library(ggplot2)
library(splstyle)

q <- ggplot()
q <- q + geom_polygon(data = pd, aes( x = long, y = lat, group = group, fill=category_with_missing), color="black", size=0.2)
q <- q + theme_void()
q <- q + coord_quickmap()
q <- q + splstyle::scale_fill_fhi("Category",palette = "map_seq_missing", direction = 1, drop=F)
q <- q + labs(title = "Palette = map_seq_missing")
q
```

```{r fig.height=7, fig.width=7}
library(ggplot2)
library(splstyle)

q <- ggplot()
q <- q + geom_polygon(data = pd, aes( x = long, y = lat, group = group, fill=category_with_missing), color="black", size=0.2)
q <- q + theme_void()
q <- q + coord_quickmap()
q <- q + splstyle::scale_fill_fhi("Category",palette = "map_seq_missing_x2", direction = 1, drop=F)
q <- q + labs(title = "Palette = map_seq_missing_x2")
q
```

```{r fig.height=7, fig.width=7}
library(ggplot2)
library(splstyle)

q <- ggplot()
q <- q + geom_polygon(data = pd, aes( x = long, y = lat, group = group, fill=category_with_missing), color="black", size=0.2)
q <- q + theme_void()
q <- q + coord_quickmap()
q <- q + splstyle::scale_fill_fhi("Category",palette = "map_seq_x2_missing", direction = 1, drop=F)
q <- q + labs(title = "Palette = map_seq_x2_missing")
q
```

```{r fig.height=7, fig.width=7}
library(ggplot2)
library(splstyle)

q <- ggplot()
q <- q + geom_polygon(data = pd, aes( x = long, y = lat, group = group, fill=category_with_missing), color="black", size=0.2)
q <- q + theme_void()
q <- q + coord_quickmap()
q <- q + splstyle::scale_fill_fhi("Category",palette = "map_seq_x2_missing_x2", direction = 1, drop=F)
q <- q + labs(title = "Palette = map_seq_x2_missing_x2")
q
```
