---
title: "Themes"
author: "Author"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 6
vignette: >
  %\VignetteIndexEntry{Themes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ggplot2)
library(splstyle)
```

## Points

```{r}
q <- ggplot(diamonds[1:200,], aes(carat, depth, color = cut))
q <- q + geom_point(size = 4)
q <- q + splstyle::scale_color_fhi(palette = "primary")
q <- q + labs(title="Theme: 'theme_fhi_basic'")
q <- q + splstyle::theme_fhi_basic()
q
```

```{r}
q <- ggplot(diamonds[1:200,], aes(carat, depth, color = cut))
q <- q + geom_point(size = 4)
q <- q + splstyle::scale_color_fhi(palette = "primary")
q <- q + labs(title="Theme: 'theme_fhi_lines'")
q <- q + splstyle::theme_fhi_lines()
q
```

```{r}
q <- ggplot(diamonds[1:200,], aes(carat, depth, color = cut))
q <- q + geom_point(size = 4)
q <- q + splstyle::scale_color_fhi(palette = "primary")
q <- q + labs(title="Theme: 'theme_fhi_lines_horizontal'")
q <- q + splstyle::theme_fhi_lines_horizontal()
q
```

## Barcharts

We first try some barcharts with the `dis_primary` palette and two different themes:

```{r}
q <- ggplot(diamonds, aes(x=color, fill = cut))
q <- q + geom_bar()
q <- q + splstyle::scale_fill_fhi(palette = "primary")
q <- q + labs(title="Theme: 'theme_fhi_basic'")
q <- q + splstyle::theme_fhi_basic()
q
```

```{r}
q <- ggplot(diamonds, aes(x=color, fill = cut))
q <- q + geom_bar()
q <- q + splstyle::scale_fill_fhi(palette = "primary")
q <- q + labs(title="Theme: 'theme_fhi_lines'")
q <- q + splstyle::theme_fhi_lines()
q
```

```{r}
q <- ggplot(diamonds, aes(x=color, fill = cut))
q <- q + geom_bar()
q <- q + splstyle::scale_fill_fhi(palette = "primary")
q <- q + labs(title="Theme: 'theme_fhi_lines_horizontal'")
q <- q + splstyle::theme_fhi_lines_horizontal()
q
```
